language: php

sudo: false

php:
  - "5.3"

cache:
 directories:
    - node_modules

env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - GIT_COMMITTER_NAME=torounit
    - GIT_COMMITTER_EMAIL=mail@torounit.com
    - GIT_AUTHOR_NAME=torounit
    - GIT_AUTHOR_EMAIL=mail@torounit.com

before_script:
  - nvm install 5
  - npm install
  - npm run build
  - composer install

script:
#  - ls -al assets/dist/styles/all.min.css
#  - ls -al assets/dist/scripts/all.min.js
  # Search for PHP syntax errors.
  - find . -path './vendor' -prune -o -name '*.php' -exec php -lf {} \;
  - composer phpcs

after_success:
- bash ./bin/deploy.sh
